export enum ActionTypes {
  CHANGE_INPUT = 'CHANGE_INPUT',
  LOAD_LEADERBOARD = 'LOAD_LEADERBOARD',
  SEARCH_USER = 'SEARCH_USER',
  CLEAR_SEARCH = 'CLEAR_SEARCH',
  SORT_USERS = 'SORT_USERS',
  CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER',
  CHANGE_PAGE = 'CHANGE_PAGE',
}
